services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      mkdir -p /opt/render/project/src/database
      touch /opt/render/project/src/database/database.sqlite
      php artisan config:clear
      php artisan migrate --force
      php artisan config:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000